### ISSUE TITLE
[ suggestions ] enabled_plugins is not installed by default (config.toml) and completions

### ISSUE THREAD

**Issue by micisse** [triyanox/lla#62]
Hello, as part of an _automated installation_ and in the case of “**lla**”, I use the configuration file with fields that can be dynamic. For example, when I set the default list to

```toml
...
default_sort = "{{ var_dynamic_field_for_example }}"          # Possible values: "name", "size", "date"
enabled_plugins = ["git_status", "file_hash", "sizeviz"]  # List of enabled plugins
...
```
**All specified plugins are not installed by default, the specified Plugins folder is empty and I have received a warning**. 
![Capture d’écran_2024-12-16_14-58-22](https://github.com/user-attachments/assets/fa38896d-033a-4ca6-ad7b-ebbed21fe9bf)
![Capture d’écran_2024-12-16_15-13-47](https://github.com/user-attachments/assets/b8832229-9d7d-4802-a170-553221846950)

I have to install them manually. 

* Perhaps a suggestion would be to allow full installation of all plugins specified in the configuration with URLS (github or other) as part of a plugin external to “**lla**” or developed by others.

For example:
```toml
...
enabled_plugins = ["categorizer <https://path.to/categorizer>", "file_hash <url>", ...etc]  # List of enabled plugins
# or URLs directly, knowing that plugins have a basic structure
enabled_plugins = ["https://path.to/...", ...etc]  # List of enabled plugins
...
```
* Another suggestion that could also improve the tool is autocompletion. I saw at **eza**, for example, a “**[completions](https://github.com/eza-community/eza/tree/main/completions)**” folder for bash, zsh ...etc. This can be useful and should also be avoided `lla --help`
![Capture d’écran_2024-12-16_15-05-08](https://github.com/user-attachments/assets/d93c4344-1277-414c-b329-5edfbde69e53)

```bash
lla <tab to see options list or completions>
```
